### ISSUE TITLE
Remove unused code - breaking change!

### ISSUE THREAD

**Issue by boydm** [boydm/scenic_math#5]

**Comment by boydm** [comment]
OK, so... Scenic_math is the only library I didn't get to in the big code cleanup leading up to the reveal at ElixirConf. It has a LOT of code in it that was from old versions or experiments and don't want to have to support it into the future. The changes are all along the lines of deleting modules and functions that Scenic doesn't use.

If people have an opinion here, I'd like to here it before I start slashing the code that is unused by Scenic.

**Comment by ijcd** [comment]
Tag/Branch it for posterity and nuke what you don't need.

**Comment by boydm** [comment]
Good plan. just branched v0.7.1 for posterity

**Comment by boydm** [comment]
The updated code will be released in 0.8.0
